name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install TA-Lib dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y python3-dev
        sudo apt-get install -y gfortran
        sudo apt-get install -y libatlas-base-dev
        sudo apt-get install -y wget
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install ta-lib
        pip install ib_insync
        pip install backtrader
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        source venv/bin/activate
        pip install pyinstaller

    - name: Build Executable with PyInstaller
      run: |
        source venv/bin/activate
        pyinstaller --onefile main.py

    - name: Install xvfb
      run: |
        sudo apt-get install -y xvfb

    - name: Test Executable
      run: |
        sudo xvfb-run --auto-servernum timeout 5m ./dist/main  # On Windows, use `dist\main.exe`
